repos:
-   repo: https://github.com/pre-commit/pre-commit
    rev: v2.1.1
    hooks:
    -   id: validate_manifest

-   repo: local
    hooks:
    -   id: shellcheck
        name: shellcheck
        language: docker_image
        entry: koalaman/shellcheck:stable
        types: [shell]
