language: shell
os: linux

services:
  - docker

jobs:
  include:
    - stage: Build

      # This must weirdly not have a dash, otherwise an empty job is created
      env: BUILD=linux
    - env: BUILD=windows
    - env: BUILD=armv6hf
    - env: BUILD=aarch64
    - env: BUILD=osx
      os: osx

    - stage: Deploy docker image
      # Don't try to run this on pull_request which hides secret env vars.
      if: branch = master AND type = push
      script:
        - source ./.multi_arch_docker
        - set -ex; multi_arch_docker::main; set +x

    # Run pre-commit checks with the shellcheck docker package that was just
    # deployed.
    - stage: Pre-commit checks
      language: python
      python: 3.7
      cache:
        - pip
        - directories: $HOME/.cache/pre-commit
      install: pip install pre-commit
      script: |
        # Run pre-commit. It also uses shellcheck on itself from the just built
        # and deployed docker image.
        # Use the first build tag, or if there isn't any use 'latest'.
        set -e
        tag="$(echo "${TAGS/ */}")"
        tag="${tag:-latest}"
        echo "tag: $tag"
        sed -i.bak -e "s/\(shellcheck\):.*/\1:$tag/" .pre-commit-config.yaml
        pre-commit run --all-files --show-diff-on-failure --color=always
        mv .pre-commit-config.yaml.bak .pre-commit-config.yaml
      after_success:  # do nothing

before_install: |
  DOCKER_BASE="$DOCKER_USERNAME/shellcheck"
  DOCKER_BUILDS=""
  export TAGS=""
  test "$TRAVIS_BRANCH" = master && TAGS="$TAGS latest" || true
  test -n "$TRAVIS_TAG"          && TAGS="$TAGS stable $TRAVIS_TAG" || true
  echo "Tags are $TAGS"
  set -e
  # The version encoded in pre-commit and built version must be in sync. If not,
  # the pre-commit version was forgotten to be updated.
  if [ -n "$TRAVIS_TAG" ]; then
    precommit_tag="$(awk -F: '/^ *entry:/ {print $NF}' .pre-commit-hooks.yaml)"
    test "$TRAVIS_TAG" = "$precommit_tag"
  fi

script:
  - mkdir -p deploy
  - source ./.compile_binaries
  - ./striptests
  - set -ex; build_"$BUILD"; set +x;
  - ./.prepare_deploy
  - ./.github_deploy

after_failure: |
  id
  pwd
  df -h
  find . -name '*.log' -type f -exec grep "" /dev/null {} +
  find . -ls

deploy:
  provider: gcs
  skip_cleanup: true
  access_key_id: GOOG7MDN7WEH6IIGBDCA
  secret_access_key:
    secure: Bcx2cT0/E2ikj7sdamVq52xlLZF9dz9ojGPtoKfPyQhkkZa+McVI4xgUSuyyoSxyKj77sofx2y8m6PJYYumT4g5hREV1tfeUkl0J2DQFMbGDYEt7kxVkXCxojNvhHwTzLFv0ezstrxWWxQm81BfQQ4U9lggRXtndAP4czZnOeHPINPSiue1QNwRAEw05r5UoIUJXy/5xyUrjIxn381pAs+gJqP2COeN9kTKYH53nS/AAws29RprfZFnPlo7xxWmcjRcdS5KPdGXI/c6tQp5zl2iTh510VC1PN2w1Wvnn/oNWhiNdqPyVDsojIX5+sS3nejzJA+KFMxXSBlyXIY3wPpS/MdscU79X6Q5f9ivsFfsm7gNBmxHUPNn0HAvU4ROT/CCE9j6jSbs5PC7QBo3CK4++jxAwE/pd9HUc2rs3k0ofx3rgveJ7txpy5yPKfwIIBi98kVKlC4w7dLvNTOfjW1Imt2yH87XTfsE0UIG9st1WII6s4l/WgBx2GuwKdt6+3QUYiAlCFckkxWi+fAvpHZUEL43Qxub5fN+ZV7Zib1n7opchH4QKGBb6/y0WaDCmtCfu0lppoe/TH6saOTjDFj67NJSElK6ZDxGZ3uw4R+ret2gm6WRKT2Oeub8J33VzSa7VkmFpMPrAAfPa9N1Z4ewBLoTmvxSg2A0dDrCdJio=
  bucket: shellcheck
  local_dir: deploy
  on:
    repo: koalaman/shellcheck
    condition: $TRAVIS_BUILD_STAGE_NAME = Build
    all_branches: true
